import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/NavbarSection";
import FooterSection from "@/components/footer/FooterSection";

export const metadata: Metadata = {
  title: "Pandu Putra Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}